CREATE TABLE RVC_EMOTE
(
    ID       UUID PRIMARY KEY,
    MEDIA_ID UUID NOT NULL,
    ENTITY   UUID,
    CONTENT  VARCHAR(1024),
    CONSTRAINT FK_RVC_EMOTE_MEDIA
        FOREIGN KEY (MEDIA_ID)
            REFERENCES RVC_MEDIA_DATA (ID)
            ON DELETE CASCADE
);

CREATE TABLE RVC_EMOTE_KEYWORDS
(
    EMOTE_ID UUID         NOT NULL,
    KEYWORD  VARCHAR(255) NOT NULL,
    CONSTRAINT PK_RVC_EMOTE_KEYWORDS PRIMARY KEY (EMOTE_ID, KEYWORD),
    CONSTRAINT FK_RVC_EMOTE_KEYWORDS_EMOTE
        FOREIGN KEY (EMOTE_ID)
            REFERENCES RVC_EMOTE (ID)
            ON DELETE CASCADE
);
