package fr.revoicechat.core.web.api;

import java.util.List;
import java.util.UUID;
import jakarta.ws.rs.DELETE;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;

import org.eclipse.microprofile.openapi.annotations.Operation;
import org.eclipse.microprofile.openapi.annotations.responses.APIResponse;
import org.eclipse.microprofile.openapi.annotations.tags.Tag;
import org.eclipse.microprofile.openapi.annotations.tags.Tags;

import fr.revoicechat.core.representation.invitation.InvitationRepresentation;

@Tag(name = "Invitation", description = "Endpoints for server or application invitations")
@Path("invitation")
public interface InvitationLinkController extends LoggedApi {

  @Operation(summary = "Generate an invitation to join the application",
      description = "Generate an invitation to join the application.")
  @APIResponse(responseCode = "200", description = "invitation successfully generated")
  @POST
  @Path("/application")
  InvitationRepresentation generateApplicationInvitation();

  @Tags(refs = { "Server", "Invitation" })
  @Operation(summary = "Generate an invitation to join a server",
      description = "Generate an invitation to join a server.")
  @APIResponse(responseCode = "200", description = "invitation successfully generated")
  @POST
  @Path("/server/{serverId}")
  InvitationRepresentation generateServerInvitation(@PathParam("serverId") UUID serverId);

  @Tags(refs = { "Server", "Invitation" })
  @Operation(summary = "Get all invitations for a server",
      description = "Get all invitations for a server")
  @APIResponse(responseCode = "200", description = "invitations successfully retrieved")
  @GET
  @Path("/server/{serverId}")
  List<InvitationRepresentation> getAllServerInvitations(@PathParam("serverId") UUID serverId);

  @Operation(summary = "Get an invitation status", description = "Get an invitation status.")
  @APIResponse(responseCode = "200", description = "invitation successfully retrived")
  @GET
  @Path("/{id}")
  InvitationRepresentation get(@PathParam("id") UUID id);

  @Operation(summary = "Get all invitation generated by a specific user",
      description = "Get all invitation generated by a specific user.")
  @APIResponse(responseCode = "200", description = "invitations successfully retrived")
  @GET
  List<InvitationRepresentation> getAll();

  @Operation(summary = "Get all application invitations", description = "Get all application invitations")
  @APIResponse(responseCode = "200", description = "invitations successfully retrived")
  @GET
  @Path("/application")
  List<InvitationRepresentation> getAllApplicationInvitations();

  @Operation(summary = "Revoke an unused invitation", description = "Revoke an unused invitation.")
  @APIResponse(responseCode = "200", description = "invitation successfully revoked")
  @DELETE
  @Path("/{id}")
  void revoke(@PathParam("id") UUID id);
}
