package fr.revoicechat.core.nls;

import fr.revoicechat.i18n.LocalizedMessage;

public enum HttpStatusErrorCode implements LocalizedMessage {
  UNAUTHORIZED_TITLE,
  UNAUTHORIZED_MESSAGE,
  FORBIDDEN_TITLE,
  FORBIDDEN_MESSAGE,
  NOT_FOUND_TITLE,
  NOT_FOUND_MESSAGE,
  METHOD_NOT_ALLOWED_TITLE,
  METHOD_NOT_ALLOWED_MESSAGE,
  INTERNAL_SERVER_ERROR_TITLE,
  INTERNAL_SERVER_ERROR_MESSAGE,

  DOCUMENTATION_API_LINK,

}
